name: bodacious
description: A bodacious music player.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# Increment the build number (after +) by at least one for every release.
# Follow semver.
version: 0.0.1+1

environment:
  sdk: ">=2.17.0-150.0.dev <3.0.0"

dependencies:
  # Audio Player Deps
  just_audio: ^0.9.20
  #just_audio_libwinmedia: ^0.0.4
  #just_audio_background: ^0.0.1-beta.5
  audio_service: ^0.18.4
  
  # Widget & Flutter Deps
  go_router: ^3.0.5
  image: ^3.1.3
  #bitsdojo_window: ^0.1.1+1
  material_design_icons_flutter: '5.0.6595'
  palette_generator: ^0.3.3
  #flutter_riverpod: ^1.0.3
  flutter_riverpod: ^2.0.0-dev.5
  flutter:
    sdk: flutter
  freezed_annotation:
  json_annotation: ^4.4.0
  path_provider: ^2.0.9

  # Library & Metadata Deps
  file_picker: ^4.5.1 # for picking directories (and files in early versions)
  #whatever library database on this line
  id3: ^1.0.2
  integer: ^2.0.1
  flac_metadata: #^1.0.4
    git: https://github.com/bleonard252/flac_metadata
  sembast: ^3.2.0
  mime: ^1.0.1
  #on_audio_query: ^2.6.0 # for finding songs from Android and iOS system libraries

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable: ^6.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.1

  # See `analysis_options.yaml`
  flutter_lints: ^1.0.0

flutter_app_name:
  name: "Bodacious"
flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/brand/ic_background.png"
  adaptive_icon_foreground: "assets/brand/ic_foreground.png"
  image_path: "assets/brand/ic_launcher.png"

flutter:
  uses-material-design: true
  # Please use `MdiIcons` instead for consistency.

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bubblebg.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # https://flutter.dev/assets-and-images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
