name: bodacious
description: A bodacious music player.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# Increment the build number (after +) by at least one for every release.
# Follow semver.
version: 0.8.0+7

environment:
  sdk: ">=2.17.0-150.0.dev <3.0.0"

dependencies:
  # Audio Player Deps
  just_audio: ^0.9.20
  just_audio_mpv: ^0.1.5
  #just_audio_libwinmedia: ^0.0.4
  #just_audio_background: ^0.0.1-beta.5
  audio_service: ^0.18.4
  
  # Widget & Flutter Deps
  go_router: ^3.0.5
  image: ^3.1.3
  #bitsdojo_window: ^0.1.1+1
  material_design_icons_flutter: '5.0.6595'
  simple_icons: ^6.13.0
  palette_generator: ^0.3.3
  #flutter_riverpod: ^1.0.3
  flutter_riverpod: ^2.0.0-dev.5
  flutter:
    sdk: flutter
  freezed_annotation:
  json_annotation: ^4.4.0
  path_provider: ^2.0.9
  rxdart: ^0.27.3
  url_launcher: ^6.1.0
  flinq: ^2.0.2
  pinelogger: ^1.1.0
  pinelogger_flutter: ^1.0.0

  # Service Deps
  dart_discord_rpc:
    git: https://github.com/alexmercerind/dart_discord_rpc
  xml: ^5.1.2
  lastfm: ^0.0.5
  spotify: ^0.7.0
  dio: ^4.0.6

  # Library & Metadata Deps
  file_picker: ^4.5.1 # for picking directories (and files in early versions)
  #whatever library database on this line
  id3: ^1.0.2
  integer: ^2.0.1
  flac_metadata: #^1.0.4
    git: https://github.com/bleonard252/flac_metadata
  mime: ^1.0.1
  #on_audio_query: ^2.6.0 # for finding songs from Android and iOS system libraries
  fuzzywuzzy: ^0.2.0

  # Database deps
  drift: ^1.6.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.1
  shared_preferences: ^2.0.13
  window_manager: ^0.2.3
  nanoid: ^1.0.0

dependency_overrides:
  xml: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable: ^6.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.1
  drift_dev: ^1.6.0

  # For testing
  mocktail: ^0.3.0

  # See `analysis_options.yaml`
  flutter_lints: ^1.0.0

flutter_app_name:
  name: "Bodacious"
flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/brand/ic_background.png"
  adaptive_icon_foreground: "assets/brand/ic_foreground.png"
  image_path: "assets/brand/ic_launcher.png"

flutter:
  uses-material-design: true
  # Please use `MdiIcons` instead for consistency.

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/bubblebg.png
    - assets/brand/ic_foreground.png
    - assets/version.txt

    # LICENSE
    # The Error Pineapple character and art are © 2022 Blake Leonard, All Rights Reserved.
    # Used in Bodacious with permission.
    - assets/error_pineapple.png
    - assets/error_pineapple_excited.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # https://flutter.dev/assets-and-images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
